vim.g.nightflyCursorColor = 1
vim.g.nightflyWinSeparator = 2
vim.cmd [[colorscheme nightfly]]
vim.cmd [[highlight! link CmpItemMenu NonText]]
vim.cmd [[hi DiagnosticVirtualTextError guibg=#26202f guifg=#fc514e]]
vim.cmd [[hi DiagnosticVirtualTextWarn guibg=#223338 guifg=#e3d18a]]
vim.cmd [[hi! TSNodeKey gui=NONE guibg=NONE guifg=#f0525c cterm=NONE]]
vim.cmd [[hi! link TSNodeUnmatched NonText]]
vim.cmd [[hi! link CmpItemKindCodeium NightflyOrange]]
vim.cmd [[hi! link OilDir NightflyBlue]]
vim.cmd [[hi! link OilCreate NightflyGreen]]
vim.cmd [[hi! link OilDelete NightflyRed]]
vim.cmd [[hi! link OilMove NightflyYellow]]
vim.cmd [[hi! link OilCopy NightflyTurquoise]]
vim.cmd [[hi! link OilChange NightflyOrange]]
