vim.keymap.set('x', 'm', function()
  require('tsht').nodes()
end, { desc = 'Select ts node' })
vim.keymap.set('n', '<leader>m', function()
  require('tsht').nodes()
end, { desc = 'Select ts node' })
vim.keymap.set('o', 'n', function()
  require('tsht').nodes()
end, { desc = 'Select ts node' })
