#!/usr/bin/env zsh

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Installing $folder"
    stow -D $folder
    stow $folder
done
popd
