# currently does not work
scroll_offset = 6

xdg_open = false
use_trash = true

[display]
# ratios for parent view, current view and preview
collapse_preview = true
column_ratio = [1, 4, 4]
show_borders = true
show_hidden = false
show_icons = true
show_preview = true
tilde_in_titlebar = true
# none, absolute, relative
line_number_style = "relative"


[display.sort]
# lexical, mtime, natural
method = "natural"
case_sensitive = false
directories_first = true
reverse = false

[preview]
# max_preview_size = 2097152 # 2MB
max_preview_size = 2147483648 # 2GB
preview_images = true
preview_script = "~/.config/joshuto/preview.sh"
preview_shown_hook_script = "~/.config/joshuto/on_preview_shown"
preview_removed_hook_script = "~/.config/joshuto/on_preview_removed"

[tab]
# inherit, home, root
home_page = "home"
