#!/usr/bin/env bash

test -z "$joshuto_wrap_id" && exit 1;

path="$1"       # Full path of the previewed file
x="$2"          # x coordinate of upper left cell of preview area
y="$3"          # y coordinate of upper left cell of preview area
width="$4"      # Width of the preview pane (number of fitting characters)
height="$5"     # Height of the preview pane (number of fitting characters)


# Find out mimetype and extension
mimetype=$(file --mime-type -Lb "$path")
extension=$(/bin/echo "${path##*.}" | awk '{print tolower($0)}')

case "$mimetype" in
    image/png | image/jpeg | image/gif | image/webp)
        show_image "$path" $x $y $width $height
        ;;
    video/*)
        # image_file=$(mktemp "$joshuto_wrap_preview_meta/thumb.XXXXXX.png")
        image_file="$joshuto_wrap_preview_meta/$(echo $path | md5sum | awk '{print $1}').png"
        ffmpegthumbnailer -s0 -i "$path" -o $image_file -f 2> /dev/null
        show_image "$image_file" $x $y $width $height
        ;;
    *)
        remove_image

esac
