##########################################
## General
##########################################
lscolors_enabled = false

##########################################
## Tabs
##########################################

[tabs]
[tabs.styles]

# Style of active tab & current directory
[tabs.styles.active]
bg = "dark"
fg = "light_blue"
bold = true

# Style of inactive tabs
[tabs.styles.inactive]

# Style of the left/front tab scroll tag (when tabs overflow)
[tabs.styles.scroll_front]
fg = "yellow"
bold = true

# Style of the right/back tab scroll tag (when tabs overflow)
[tabs.styles.scroll_back]
fg = "yellow"
bold = true

[selection]
fg = "light_yellow"
bold = true
prefix = "  "
size = 2

[executable]
fg = "light_green"
bold = true

[regular]
fg = "white"

[directory]
fg = "light_blue"
bold = true

[link]
fg = "light_cyan"
bold = true

[link_invalid]
fg = "red"
bold = true

[socket]
fg = "light_magenta"
bold = true

[ext]

[ext.bmp]
fg = "yellow"
[ext.jpg]
fg = "yellow"
[ext.jpeg]
fg = "yellow"
[ext.png]
fg = "yellow"
[ext.webp]
fg = "yellow"
[ext.ppm]
fg = "yellow"
[ext.svg]
fg = "yellow"
[ext.gif]
fg = "yellow"

[ext.wav]
fg = "magenta"
[ext.flac]
fg = "magenta"
[ext.mp3]
fg = "magenta"
[ext.avi]
fg = "magenta"
[ext.m3u]
fg = "magenta"
[ext.mov]
fg = "magenta"
[ext.mp4]
fg = "magenta"
[ext.mkv]
fg = "magenta"
[ext.m4a]
fg = "magenta"
[ext.ts]
fg = "magenta"
[ext.webm]
fg = "magenta"
[ext.wmv]
fg = "magenta"

[ext.7z]
fg = "red"
[ext.zip]
fg = "red"
[ext.bz2]
fg = "red"
[ext.gz]
fg = "red"
[ext.tar]
fg = "red"
[ext.tgz]
fg = "red"
[ext.xz]
fg = "red"
[ext.rar]
fg = "red"
