#! /bin/sh
#
#  █  █▀ █▄▄▄▄ ▄█     ▄   ██    ▄  █ 
#  █▄█   █  ▄▀ ██      █  █ █  █   █ 
#  █▀▄   █▀▀▌  ██ █     █ █▄▄█ ██▀▀█ 
#  █  █  █  █  ▐█  █    █ █  █ █   █ 
#    █     █    ▐   █  █     █    █  
#   ▀     ▀          █▐     █    ▀   
#                    ▐     ▀         
#
# A customized bspwmrc for the bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

xrdb merge ~/.Xresources &
xsetroot -cursor_name left_ptr &
setxkbmap -option caps:ctrl_modifier &

feh --bg-fill ~/Pictures/Backgrounds/super.jpg
$HOME/.config/polybar/launch.sh --blocks &

#### AUTOSTART ####
killall -q sxhkd
sxhkd &
picom &
conky &
clipmenud &
# lxsession --noxsettings --noautostart &
killall -q mpd-notification
mpd-notification &
nitrogen --restore &
dunst &
$HOME/.local/bin/xsidle.sh betterlockscreen -l dimblur &

#### MONITORS ####
bspc monitor LVDS-1 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X

#### BSPWM configuration ####
#bspc config border_radius                 5
bspc config border_width                  2
bspc config window_gap                    8
bspc config top_padding                   15
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner

#### BSPWM coloring ####
bspc config focused_border_color          "#596bfd"
bspc config normal_border_color           "#3b455e"
bspc config active_border_color           "#596bfd"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#CB0248"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a SimpleScreenRecorder state=floating
